#!groovy
import static groovy.io.FileType.FILES

node {
   echo 'SharedFlow Deployment started...'
  
	stage ('Checkout'){
		checkout scm
	}
	
	stage ('Deploying SharedFlow'){
		def mvnHome = tool 'Maven3.3.9'
	    sh "${mvnHome}/bin/mvn --version"
		echo "${env.WORKSPACE}"
		readDir()
	}		

}
@NonCPS
def readDir()
{
    FILES_DIR = 'apigee-codegen'
    def filenames = [];
    def dir = new File("${env.WORKSPACE}/${FILES_DIR}");
	echo "dir name:: ${dir}"
    dir.traverse(type: FILES, maxDepth: 0) {
        filenames.add(it.getName())
    }

    for (int i = 0; i < filenames.size(); i++) {
        def filename = filenames[i]
        echo "${filename}"
    }
	
}
