#!groovy
import static groovy.io.FileType.FILES

node {
   echo 'SharedFlow Deployment started...'
  
	stage ('Checkout'){
		checkout scm
	}
	
	stage ('Deploying SharedFlow'){
		def mvnHome = tool 'Maven3.3.9'
	    sh "${mvnHome}/bin/mvn --version"
		echo "${env.WORKSPACE}"
		readDir()
	}		

}
@NonCPS
def readDir()
{
   def files = findFiles(glob: '**/pom.xml')
	echo "${files}"
	
}
